version: '3.8'
services:

  # imagem micro 02
  micro_02:
    build:
      args:
        user: tss
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - microservice02

  #nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - microservice02

  queue:
    build:
      args:
        user: tss
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - microservice02

  # db
  db_micro_02:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql #Database will be saved in this folder... DON'T FORGET to add it in .gitignore
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - microservice02

  # redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - microservice02

networks:
  microservice02:
    driver: bridge
